DELETE FROM tours;
DELETE FROM units;
DELETE FROM floors;
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_PB2', 'PB 2', -2, 'Sótano', '/plants/floor_pb1.png');
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_PB1', 'PB 1', -1, 'Sótano', '/plants/floor_pb.png');
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_1', '1', 1, 'Piso', '/plants/floor_1.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_1_101', 'floor_1', '101', 'APARTMENT', 1, 2.5, 108.42, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_1_102', 'floor_1', '102', 'APARTMENT', 1, 1.5, 80.11, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_2', '2', 2, 'Piso', '/plants/floor_2.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_2_201', 'floor_2', '201', 'APARTMENT', 2, 2.5, 122.82, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_2_202', 'floor_2', '202', 'APARTMENT', 2, 2.5, 134.03, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_3', '3', 3, 'Piso', '/plants/floor_3.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_3_301', 'floor_3', '301', 'APARTMENT', 2, 2.5, 122.82, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_3_302', 'floor_3', '302', 'APARTMENT', 2, 2.5, 134.03, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_4', '4', 4, 'Piso', '/plants/floor_4.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_4_401', 'floor_4', '401', 'APARTMENT', 2, 2.5, 122.82, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_4_402', 'floor_4', '402', 'APARTMENT', 2, 2.5, 134.03, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_5', '5', 5, 'Piso', '/plants/floor_5.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_5_501', 'floor_5', '501', 'APARTMENT', 3, 2, 250.95, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_5_502', 'floor_5', '502', 'APARTMENT', 2, 2, 267.89, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_6', '6', 6, 'Piso', '/plants/floor_6.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_6_601', 'floor_6', '501', 'APARTMENT', 3, 2, 250.95, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_6_602', 'floor_6', '502', 'APARTMENT', 2, 2, 267.89, NULL, 'AVAILABLE', NULL);
